# Site settings
title: Personal Statement
description: Highlight of individual Performance
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ryan Ashiruma
user_description: Total of one year experience that spans through a range of industries including agricultural and food processing industry to Systems analysis , design , software development and deployment. 90% of experience is focused on enterprise systems software development.
user_title: Software Developer
email: ryananayngu@gmail.com
github_username:  ryananyangu
gplus_username:  ryananyangu

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
